import Head from "next/head";
import DefaultLayout from "../components/DefaultLayout";
import styles from "../styles/Home.module.css";
import useTranslation from "next-translate/useTranslation";

export default function Horeca() {
  let { t } = useTranslation();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        <main className={styles.main}>
          <h1 className={styles.title}>{t("common:greeting")}</h1>
        </main>
      </DefaultLayout>
    </div>
  );
}
