import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import DefaultLayout from "../components/DefaultLayout";
import styles from "../styles/Home.module.css";
import useTranslation from "next-translate/useTranslation";
import {
  FContainer,
  FleftSide,
  FrightSide,
  FSection,
} from "../elements/elements";

export default function Home() {
  let { t } = useTranslation();
  return (
    <div className={styles.container}>
      <Head>
        <title>Fitides Bakery | Pitta Bread</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <main className={styles.main}>
          <FSection>
            <FContainer>
              <FleftSide>
                <h1 className={styles.title}>{t("common:greeting")}</h1>
                <p>hello</p>
              </FleftSide>
              <FrightSide>Right Side</FrightSide>
            </FContainer>
          </FSection>
        </main>
      </DefaultLayout>
    </div>
  );
}
